### ISSUE TITLE
Error using the phar

### ISSUE THREAD

**Issue by ericovasconcelos** [zfcampus/zf-deploy#44]
Hi,

I've tried to use the zfdeploy tool and it seams to be reaching the composer.par using a direct folder path. In my case it throws the following error:

Mufasa:pacotes erico$ sudo ./zfdeploy.phar build arch.zpk --target /Users/erico/Downloads/pacotes/archetypebasezf
Creating package "arch.zpk"...
Executing /var/tmp//ZFDeploy_55ae5350580ee/data/composer.phar install --no-dev --prefer-dist --optimize-autoloader 2>&1
Composer error during install command (exit code: 2)
Mufasa:pacotes erico$

**Comment by kachar** [comment]
I get similar error when using the `zfdeploy.phar`

```
[22.07.2015 17:15:26] (13598) ERROR: Zend Deployment Exception: Unable to find application dir 'data' in the package
[22.07.2015 17:15:26] (13598) ERROR: #0 /usr/local/zend/gui/vendor/ZendDeployment/src/ZendDeployment/PackageFile.php(169): ZendDeployment_PackageFile->readDescriptorFile('/usr/local/zend...', '/usr/local/zend...')
#1 /usr/local/zend/gui/vendor/ZendDeployment/src/ZendDeployment/PackageFile.php(466): ZendDeployment_PackageFile->loadFile('/usr/local/zend...')
#2 /usr/local/zend/gui/module/Deployment/src/Deployment/Application/Package.php(45): ZendDeployment_PackageFile::isValid('/usr/local/zend...')
#3 /usr/local/zend/gui/module/Deployment/src/Deployment/Controller/WizardController.php(421): Deployment\Application\Package::isValid('/usr/local/zend...')
#4 /usr/local/zend/gui/vendor/ZF2/library/Zend/Mvc/Controller/AbstractActionController.php(83): Deployment\Controller\WizardController->uploadAction()
#5 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
```
